[[Zvqdotq,Zvqdotq]]
=== `Zvqdotq` - Vector quad widening 4D Dot Product


8-bit Integer dot-product instructions performing the dot product between two 4-element vectors of 8-bit integer elements and accumulating it into a 32-bit integer accumulator.

`SEW` is used to indicate both the size of the accumulator elements and the size of the 4-element byte vectors.
These instructions are only defined for `SEW`=32.

These vector dot product instructions are defined with a fixed SEW value of 32. They work on an element group with four 8-bit values stored together in a 32-bit bundle. For each input bundle for the dot product there is a corresponding (same index) SEW-wide element in the accumulator source (and destination). The “q” in the mnemonic indicates that the instruction is quad-widening.

The number of body bundles is determined by `vl`. The operation can be masked, each mask bit determines whether the corresponding element result is active or not.

NOTE::
Future variants could be defined for different SEW values thus:
[%autowidth]
[%header,cols="^2,4"]
|===
|	SEW | values
|	32	| 8-bit
|	64	| 16-bit
|	16	| 4-bit
|===

All the instructions defined in this extension fall into two schemes: vector-vector or vector-scalar.


.Vector Scalar data layout
image::vqdotq_vqdot_vx.svg[width=60%]

.Vector Vector data layout
image::vqdotq_vqdot_vv.svg[width=60%]


[%autowidth]
[%header,cols="^2,4"]
|===
|Mnemonic
|Instruction
| vqdot.[vv,vx]   | <<insns-vqdot>>
| vqdotu.[vv,vx]  | <<insns-vqdotu>>
| vqdotsu.[vv,vx] | <<insns-vqdotsu>>
| vqdotus.vx      | <<insns-vqdotus>>

|===
